[project]
name = "imdb1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "asnganje", email = "abd.nganje@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-auth>=2.58.0",
    "google-auth-oauthlib>=1.4.1",
    "gspread>=6.2.1",
    "openpyxl>=3.1.5",
    "scrapy>=2.19.0",
    "scrapy-playwright>=0.0.48",
]

[project.scripts]
imdb1 = "imdb1:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
